/*
 * Copyright © 2022-2025 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.metreeca.mesh.meta.jsonld;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Container annotation for multiple {@link Namespace} annotations.
 *
 * <p>This is a container annotation that holds multiple {@link Namespace} annotations when
 * applied to a single {@link Frame} interface. It is automatically generated by the Java compiler when multiple
 * {@code @Namespace} annotations are applied to a single element.</p>
 *
 * @see Namespace
 */
@Target(TYPE)
@Retention(RUNTIME)
public @interface Namespaces {

    /**
     * Retrieves the array of namespace annotations.
     *
     * @return the array of contained {@link Namespace} annotations
     */
    Namespace[] value();

}
