name: maven-snapshot

on:

  push:
    branches:
      - release/*

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USR
          server-password: OSSRH_PWD
          gpg-private-key: ${{ secrets.MAVEN_KEY }}
          gpg-passphrase: MAVEN_PWD

      - name: Release snapshot to ossrh
        env:
          OSSRH_USR: ${{ secrets.OSSRH_USR }}
          OSSRH_PWD: ${{ secrets.OSSRH_PWD }}
          MAVEN_PWD: ${{ secrets.MAVEN_PWD }}
        run: mvn --batch-mode
          --activate-profiles release
          -Drevision="$(echo ${{ github.ref_name }} | sed -r 's:^release/(.*)$:\1-SNAPSHOT:')"
          deploy
