name: maven-version

on:

  push:
    tags:
      - v*

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up java environment
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CENTRAL_USR
          server-password: CENTRAL_PWD
          gpg-private-key: ${{ secrets.MAVEN_KEY }}
          gpg-passphrase: MAVEN_PWD

      - name: Publish version to Central Portal
        env:
          CENTRAL_USR: ${{ secrets.CENTRAL_USR }}
          CENTRAL_PWD: ${{ secrets.CENTRAL_PWD }}
          MAVEN_PWD: ${{ secrets.MAVEN_PWD }}
        run: mvn --batch-mode
          --activate-profiles publih
          -Drevision="$(echo ${{ github.ref_name }} | sed -r 's:^v?(.*)$:\1:')"
          deploy
